# Generated by Django 3.2 on 2023-08-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
