# Generated by Django 3.2 on 2023-08-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_auto_20230819_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecategory',
            options={'verbose_name': 'Категория цен', 'verbose_name_plural': 'Категории цен'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='flowers.ProductCategory', verbose_name='Категории букетов'),
        ),
    ]
