# Generated by Django 3.2 on 2023-08-19 21:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0011_auto_20230819_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Необработан'), ('ready', 'Готов')], db_index=True, default='new', max_length=20, null=True, verbose_name='Статус заказа')),
                ('firstname', models.CharField(max_length=90, null=True, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('registration_date', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Дата регистрации')),
                ('call_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата звонка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заявке')),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультации',
            },
        ),
    ]
